### ISSUE TITLE
sV scan become overwritten

### ISSUE THREAD

**Issue by evs-as** [evait-security/envizon#14]
### Description

the results of an sV scan are overwritten when a simple scan is performed afterwards

### Steps to Reproduce

- scan an open port with ```-sV``` becomes:
```80 | http | Apache httpd```
- default scan of the same port becomes:
```80 | http | Unknown Product```

### Idea to fix

- only overwrite alrady exists ports if the new scan used the sV parameter

**Comment by evs-pn** [comment]
fixed in #19
