### ISSUE TITLE
Paralell scans seams not working

### ISSUE THREAD

**Issue by evs-as** [evait-security/envizon#15]
### Description

It looks like the scans are starting one at a time and the setting for paralell scans will be ignored in the backend.

### Steps to Reproduce

- increase paralell scans to 3 in the setting tab.
- start a large scan eg. ```-sV -p-``` on a target
- start a small scan eg. ```-p 80``` on the same target
- check the runnig scans in the frondend (only the first start)
- verify the running processes with ```top``` in the docker container (only the first is running)
- kill the large scan in terminal or wait until it becomes finished
- verify the start / end date of the finished scans (smal scan started at the moment wenn the lage scan is finished / canceled)

**Comment by blacklist-arcc** [comment]
moved to sidekiq
