### ISSUE TITLE
add masscan

### ISSUE THREAD

**Issue by blacklist-arcc** [evait-security/envizon#28]
Scanning large networks with nmap is not recommend. We will add an individual masscan interface soon. Hold on!

**Comment by menzow** [comment]
Would love to see masscan added! In the mean time have you considered spawning multiple nmap processes to distribute the scan? In theory it sounds inefficient but it works surprisingly well in practice.

In bash that looks something like this:
```
cat ip-ranges.txt | xargs -P128 -I{} bash -c 'results=$(nmap -F $0) && echo "$results" > /tmp/scan-results.txt'
```
Here a list of ip addresses or ranges is piped into xargs which will run 128 parallel nmap instances to scan the targets. Once the scan is completed the entire output is appended to /tmp/scan-results.txt.

**Comment by evs-ch** [comment]
Splitting the scans sounds like a good solution in the interim, thanks!

Currently the parallel scanning in envizon is somewhat unreliable, but fixing that and improving the way scans are handled (ie. make it possible to cancel scans properly) is one of the next things to be done. Once that's done, implementing an option to split (larger) should be a quick thing to add.

**Comment by evs-pn** [comment]
similar to #10

**Comment by blacklist-arcc** [comment]
scan splitting was added in 3.0. Masscan will not work because envizon requires the full power of software detection and scripts from nmap
