### ISSUE TITLE
adding cytoscape networkmap support

### ISSUE THREAD

**Issue by evs-cp** [evait-security/envizon#39]
For a decent network graph, open source js libary cytoscape can be used.

https://github.com/cytoscape/cytoscape.js

**Comment by evs-pn** [comment]
I think one of the main problems is visualizing a whole network in a generic way. Every infrastructure has its own layout and properties. With envizon you can group each target and flag them with casual security issues to get a nice overview. Visualizing a network with graphs would not be helpful for blue or red teams. Maybe the community have some great ideas to visualize a network in that way.
