### ISSUE TITLE
modal not close while move to new group

### ISSUE THREAD

**Issue by evs-as** [evait-security/envizon#40]
### Description

The Funktion "Add new Group" do not close the modal, if "move" is selected. maybe the issue only triggers in virtuell Groups(custom Search).

in backgroud the funktion seems to work (if you reload the page all seams fine)

### Steps to Reproduce

- search something and Click "Add to Group View"
- select some Targets and click "add new group with selected clients"
- prefill all inputfields, select "move" and submit the modal

**Comment by evs-pn** [comment]
the issue appears only with virtual groups like a search result. I will digg into this
