### ISSUE TITLE
Running from local git checkout

### ISSUE THREAD

**Issue by noraj** [evait-security/envizon#69]
### Description

[Running from local git checkout](https://github.com/evait-security/envizon#running-from-local-git-checkout) steps are not correct or envizon_local docker image is bugged.

https://0bin.net/paste/OOsvz6EW#rxj9slgkdPfhMz+9uCYUpf-DhKJ3an3VJd0P4ghxd8L

The idea is that the key `.ssl/localhost.key` is missing.

https://github.com/evait-security/envizon/blob/b786c6c0749a0d725be72808ea0498cd3ed6a827/docker/envizon_local/entrypoint_local.sh#L4-L11

It means the entrypoint script is not working as intended.

And effectively at the beginning I can see:

```
envizon_local      | No certificates provided and none in .ssl/, generating some for you                                                                                                                                                     
envizon_local      | Generating a RSA private key                                                                                                                                                                                            
envizon_local      | ...+++++
envizon_local      | .............................+++++
envizon_local      | writing new private key to '.ssl/localhost.key'
envizon_local      | req: Can't open ".ssl/localhost.key" for writing, No such file or directory
```

If it can't ouput in an non-existing file, maybe a quick `touch` can solve that?

### Steps to Reproduce

Follow [Running from local git checkout](https://github.com/evait-security/envizon#running-from-local-git-checkout) .

**Comment by blacklist-arcc** [comment]
The issue can be reproduced. The local setup was not covered in the 3.0 to 4.0 upgrade tests. The lazy setup with prebuild images works perfectly in a clean environment as mentioned in #68 
We will fix this in the next business days.

**Comment by noraj** [comment]
This ssl folder error is no longer here but we still have this:
![image](https://user-images.githubusercontent.com/16578570/93400744-cbfbca80-f880-11ea-95f6-3e2c1a939802.png)

1. It seems envizon_local try to contact the PG DB too soon so the connection fail, a timer should be used.
2. Finally the DB is created but reaching https://localhost:3000/users/sign_in generates the error bellow

```sql
envizon_postgres_local | 2020-09-16 22:59:41.116 UTC [59] ERROR:  relation "users" does not exist at character 566
envizon_postgres_local | 2020-09-16 22:59:41.116 UTC [59] STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
envizon_postgres_local |                             pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
envizon_postgres_local |                             c.collname, col_description(a.attrelid, a.attnum) AS comment
envizon_postgres_local |                        FROM pg_attribute a
envizon_postgres_local |                        LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
envizon_postgres_local |                        LEFT JOIN pg_type t ON a.atttypid = t.oid
envizon_postgres_local |                        LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
envizon_postgres_local |                       WHERE a.attrelid = '"users"'::regclass
envizon_postgres_local |                         AND a.attnum > 0 AND NOT a.attisdropped
envizon_postgres_local |                       ORDER BY a.attnum
```

Can you reproduce this too? I removed all containers & images and used the last commit 3d43c9d492077a6558ae7373d4d9cfa4baccb910

**Comment by noraj** [comment]
I cleaned cache and it's good now.
