### ISSUE TITLE
Feature/Enhancement - IP counting improvement

### ISSUE THREAD

**Issue by KoEnix** [evait-security/envizon#74]
Hello former colleagues,
we are using envizon when pentesting, too, and my fellow colleagues are loving the tool.
But we discovered, that when working with a giant range of ip-adresses and ordering them asc. or desc, the counting of envizon seems a bit odd. For example:

192.168.0.1
192.168.0.110
192.168.0.12
192.168.0.2

Would it be possible, that envizon will count in the usual manner and consider each triple as one big number, not as three separate numbers? Thanks in advance.

**Comment by blacklist-arcc** [comment]
https://datatables.net/plug-ins/sorting/ip-address

Should be done in the next business days
