### ISSUE TITLE
Feature: Taking notes to each entry

### ISSUE THREAD

**Issue by KoEnix** [evait-security/envizon#75]
Hello again,

while using envizon, we found, that it would be an huge improvement, if it would be possible, to add notes to each entry in a seperate field. Even better, but also more complicated, would be a search feature for these notes.

Yours sincerly,
Chris

**Comment by blacklist-arcc** [comment]
The feature will be implemented soon. We just have to figure out a smart way to visualize that feature without overloading the interface.

**Comment by blacklist-arcc** [comment]
done in dev-arcc branch. will be merged to master next week
