### ISSUE TITLE
Ignore invalid SSL-Certificate - Webserver Images

### ISSUE THREAD

**Issue by s3m73x** [evait-security/envizon#83]
I have a simple feature request.
Simply let the Web-Screenshot-module ignore invalid ssl-certificates and connect to the server anyways in order to get the real-screenshot and not only the "certificate invalid" screenshot.

I have had a very short at the docker-containers and I saw u use selenium.
Maybe this will help you to ignore the self signed ssl-certs:
https://stackoverflow.com/questions/24507078/how-to-deal-with-certificates-using-selenium

**Comment by blacklist-arcc** [comment]
This feature is enabled already but I think it's not working when following redirections. Furthermore we are working on another feature to screenshot webservices using the corresponding hostname. 

This issue is already tracked internally and will be fixed soon.

**Comment by s3m73x** [comment]
Yeah but nowadays 90% of all websites use redirects in internal audits. :-S
Lookin forward for news on this might try to get a workaround fixed in myself.

**Comment by blacklist-arcc** [comment]
Not focused this issue because moving to bootstrap and recreating the UI. The issue will be focused right after release of the new version.

**Comment by blacklist-arcc** [comment]
After countless hours and coffees we finally found the missing caps.
