### ISSUE TITLE
Export nmap-results as .nmap .gnmap .xml

### ISSUE THREAD

**Issue by s3m73x** [evait-security/envizon#84]
Hi,

I really like your tool. What I do not like is that I can not export the results in their RAW-formats as well like .nmap .gnmap .xml so I cann really use my normal parsers.

Now I have to do all scanning on the commandline then download it from the remote machine where envizon runs to my local machine and upload them again to the envizon-instance. 

Would be really appreciated if you could save and then allow export of the raw nmap-output-files. Shouldnt be too much effort to include and would be highly appreciated.

**Comment by blacklist-arcc** [comment]
Thanks for your feedback and contribution. We will make a few tests...the xml files are placed in the docker container and should be easy to make them downloadable

**Comment by blacklist-arcc** [comment]
This feature will not be added. We split all nmap scans in small chunks for better performance and minimal waiting time for finished scans. All nmap scans are located inside the docker volume in nmap/uploads. You can list the files with `docker-compose exec envizon ls nmap/uploads` and can use `docker cp` to copy the files outside the container.
